name: Waka Readme (Profile Readme Development Stats)

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 03 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: TRUE
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M"
          SHOW_LINES_OF_CODE: TRUE
          SHOW_TIMEZONE: FALSE
          SHOW_LOC_CHART: FALSE
          IGNORED_REPOS: ""
          SYMBOL_VERSION: 3
